language: python
python:
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install coveralls
  - pip install pytest-cov # to get coverage report
  - pip install . # Install this package and the packages listed in requirements.txt.
  - pip install -r requirements-dev.txt # Install extra requirements for running tests and building docs.
  - sudo apt-get install pandoc

script:
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
  - flake8  # Enforce code style ('relaxed' line length limit is set in .flake8 config file).
  - make -C docs html  # Build the documentation.

after_success:
  - coveralls
  - git subtree push --prefix docs/build/html origin gh-pages
